export interface AppConfig {
  nodeEnv: 'development' | 'test' | 'staging' | 'production';
  port: number;
  apiPrefix: string;
  databaseUrl: string;
  supabaseUrl: string;
  supabaseServiceRoleKey: string;
  redisUrl: string;
  privyAppId: string;
  privyAppSecret: string;
  alchemyApiKey: string;
  sentryDsn?: string;
  posthogApiKey?: string;
  posthogHost?: string;
  arbitrumSepoliaRpcUrl: string;
  robinhoodTestnetRpcUrl: string;
  settlementPrivateKey: `0x${string}`;
  arbitrumSepoliaValenRegistry: `0x${string}`;
  arbitrumSepoliaValenSettlement: `0x${string}`;
  robinhoodTestnetValenRegistry: `0x${string}`;
  robinhoodTestnetValenSettlement: `0x${string}`;
  arbitrumSepoliaTokenSettlementAdapter?: `0x${string}`;
  robinhoodTestnetTokenSettlementAdapter?: `0x${string}`;
  robinhoodAssetRegistryAddress?: `0x${string}`;
  erc8004RegistryAddress?: `0x${string}`;
  erc8004RegistryChainId?: number;
  valenIdentityResolverAddress?: `0x${string}`;
  valenBudgetVaultAddress?: `0x${string}`;
  x402FacilitatorUrl?: string;
  operatorDashboardSecret?: string;
}
